networks:
  loki-network:

services:
  loki:
    image: grafana/loki:3.6.5
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki-network

  alloy:
    image: grafana/alloy:v1.15.1
    ports:
      - "11111:11111"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ../logs/app.log:/var/log/movie-ticket/app.log
      - ../logs/auth.log:/var/log/movie-ticket/auth.log
      - ../logs/booking.log:/var/log/movie-ticket/booking.log
      - ../logs/error.log:/var/log/movie-ticket/error.log
      - ../logs/payment.log:/var/log/payment.log
    command: run --server.http.listen-addr=0.0.0.0:11111 /etc/alloy/config.alloy
    networks:
      - loki-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki-network
    depends_on:
      - loki
